// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TWP.Api.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250912180915_addMinionHitPointColumn")]
    partial class addMinionHitPointColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TWP.Api.Core.DbEntities.ActionDbEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AttackBonus")
                        .HasColumnType("integer")
                        .HasColumnName("attack_bonus");

                    b.Property<string>("AttackType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("attack_type");

                    b.Property<int?>("DamageBonus")
                        .HasColumnType("integer")
                        .HasColumnName("damage_bonus");

                    b.Property<string>("DamageDice")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("damage_dice");

                    b.Property<string>("DamageType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("damage_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsProhibitedForMinion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_prohibited_for_minion");

                    b.Property<int?>("LimitPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("limit_per_day");

                    b.Property<string>("LongRange")
                        .HasColumnType("text")
                        .HasColumnName("long_range");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("NumberDamageDice")
                        .HasColumnType("integer")
                        .HasColumnName("number_damage_dice");

                    b.Property<string>("ShortRange")
                        .HasColumnType("text")
                        .HasColumnName("short_range");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("actionTrigger")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("action_trigger");

                    b.Property<string>("advantageCondition")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("advantage_condition");

                    b.Property<string>("disadvantageCondition")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("disadvantage_condition");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId")
                        .HasDatabaseName("IX_action_monster_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_action_name");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_action_type");

                    b.ToTable("actions", "public");
                });

            modelBuilder.Entity("TWP.Api.Core.DbEntities.Monster5eDbEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alignment")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alignment");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer")
                        .HasColumnName("armor_class");

                    b.Property<int?>("ChaSavingThrow")
                        .HasColumnType("integer")
                        .HasColumnName("cha_saving_throw");

                    b.Property<string>("ChallengeRating")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("challenge_rating");

                    b.Property<int?>("Charisma")
                        .HasColumnType("integer")
                        .HasColumnName("charisma");

                    b.Property<string>("Climb")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("climb");

                    b.Property<int?>("ConSavingThrow")
                        .HasColumnType("integer")
                        .HasColumnName("con_saving_throw");

                    b.Property<int?>("Constitution")
                        .HasColumnType("integer")
                        .HasColumnName("constitution");

                    b.Property<float>("Cr")
                        .HasColumnType("real")
                        .HasColumnName("cr");

                    b.Property<float?>("CrInLair")
                        .HasColumnType("real")
                        .HasColumnName("cr_in_lair");

                    b.Property<string>("CreatureSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("creature_size");

                    b.Property<string>("CreatureSubType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creature_sub_type");

                    b.Property<string>("CreatureType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creature_type");

                    b.Property<string>("DamageImmunities")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("damage_immunities");

                    b.Property<string>("DamageResistances")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("damage_resistances");

                    b.Property<int?>("DexSavingThrow")
                        .HasColumnType("integer")
                        .HasColumnName("dex_saving_throw");

                    b.Property<int?>("Dexterity")
                        .HasColumnType("integer")
                        .HasColumnName("dexterity");

                    b.Property<string>("Equipments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("equipments")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Fly")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fly");

                    b.Property<string>("Habitats")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("habitats");

                    b.Property<string>("HitDice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hit_dice");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer")
                        .HasColumnName("hit_points");

                    b.Property<int>("InitiativeBonus")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_bonus");

                    b.Property<int?>("IntSavingThrow")
                        .HasColumnType("integer")
                        .HasColumnName("int_saving_throw");

                    b.Property<int?>("Intelligence")
                        .HasColumnType("integer")
                        .HasColumnName("intelligence");

                    b.Property<string>("Languages")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("languages");

                    b.Property<string>("Lore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("lore")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Manner")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("manner");

                    b.Property<int?>("MinionArmorClass")
                        .HasColumnType("integer")
                        .HasColumnName("minion_armor_class");

                    b.Property<int>("MinionHitPoints")
                        .HasColumnType("integer")
                        .HasColumnName("minion_hit_points");

                    b.Property<string>("MonsterGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("monster_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("PageSource")
                        .HasColumnType("integer")
                        .HasColumnName("page_source");

                    b.Property<int?>("ProficiencyBonus")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency_bonus");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Senses")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senses");

                    b.Property<string>("Skills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("skills")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source");

                    b.Property<string>("Speed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("speed");

                    b.Property<int?>("StrSavingThrow")
                        .HasColumnType("integer")
                        .HasColumnName("str_saving_throw");

                    b.Property<int?>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.Property<string>("Swim")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("swim");

                    b.Property<int?>("WisSavingThrow")
                        .HasColumnType("integer")
                        .HasColumnName("wis_saving_throw");

                    b.Property<int?>("Wisdom")
                        .HasColumnType("integer")
                        .HasColumnName("wisdom");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeRating")
                        .HasDatabaseName("IX_monster_challenge_rating");

                    b.HasIndex("CreatureType")
                        .HasDatabaseName("IX_monster_creature_type");

                    b.HasIndex("MonsterGroup")
                        .HasDatabaseName("IX_monster_group");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_monster_name");

                    b.ToTable("monsters", "public");
                });

            modelBuilder.Entity("TWP.Api.Core.DbEntities.MonsterAideddDbEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AC")
                        .HasColumnType("integer");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HP")
                        .HasColumnType("integer");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Legendary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AideddMonsters", "public");
                });

            modelBuilder.Entity("TWP.Api.Core.DbEntities.MonsterBuildingGuidelineDbEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer")
                        .HasColumnName("armor_class");

                    b.Property<int>("AttackBonus")
                        .HasColumnType("integer")
                        .HasColumnName("attack_bonus");

                    b.Property<int>("AverageDamagePerRound")
                        .HasColumnType("integer")
                        .HasColumnName("average_damage_per_round");

                    b.Property<int>("AverageHP")
                        .HasColumnType("integer")
                        .HasColumnName("average_hp");

                    b.Property<string>("CR")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cr");

                    b.Property<float>("CRNumeric")
                        .HasPrecision(5, 3)
                        .HasColumnType("real")
                        .HasColumnName("cr_numeric");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DamagePerRound")
                        .HasColumnType("integer")
                        .HasColumnName("damage_per_round");

                    b.Property<int>("DamagePerRoundAlt")
                        .HasColumnType("integer")
                        .HasColumnName("damage_per_round_alt");

                    b.Property<string>("ExampleMonsters")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("example_monsters");

                    b.Property<int>("Exp")
                        .HasColumnType("integer")
                        .HasColumnName("exp");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer")
                        .HasColumnName("experience_points");

                    b.Property<string>("HPRange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hp_range");

                    b.Property<int>("InitiativeBonus")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_bonus");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOfficial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_official");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<int>("MinHP")
                        .HasColumnType("integer")
                        .HasColumnName("min_hp");

                    b.Property<int>("MultiAttackCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("multi_attack_count");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency_bonus");

                    b.Property<int>("SaveDC")
                        .HasColumnType("integer")
                        .HasColumnName("save_dc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source");

                    b.Property<string>("ToFHP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tof_hp");

                    b.Property<int>("TotalDamageAvg")
                        .HasColumnType("integer")
                        .HasColumnName("total_damage_avg");

                    b.Property<int>("TotalDamageLegendaryAvg")
                        .HasColumnType("integer")
                        .HasColumnName("total_damage_legendary_avg");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CR")
                        .IsUnique()
                        .HasDatabaseName("IX_guideline_cr");

                    b.HasIndex("CRNumeric")
                        .HasDatabaseName("IX_guideline_cr_numeric");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_guideline_is_active");

                    b.HasIndex("IsActive", "CRNumeric")
                        .HasDatabaseName("IX_guideline_active_cr_numeric");

                    b.ToTable("monster_building_guidelines", "public");
                });

            modelBuilder.Entity("TWP.Api.Core.DbEntities.Symbarum5eDbEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<string>("Shadow")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("shadow");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId")
                        .IsUnique()
                        .HasDatabaseName("IX_symbarum5e_monster_id");

                    b.ToTable("symbarum5es", "public");
                });

            modelBuilder.Entity("TWP.Api.Core.DbEntities.TraitDbEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AttackBonus")
                        .HasColumnType("integer")
                        .HasColumnName("attack_bonus");

                    b.Property<int?>("DamageBonus")
                        .HasColumnType("integer")
                        .HasColumnName("damage_bonus");

                    b.Property<string>("DamageDice")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("damage_dice");

                    b.Property<string>("DamageType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("damage_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsOptional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_optional");

                    b.Property<Guid>("MonsterId")
                        .HasColumnType("uuid")
                        .HasColumnName("monster_id");

                    b.Property<int?>("NumberDamageDice")
                        .HasColumnType("integer")
                        .HasColumnName("number_damage_dice");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("advantageCondition")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("advantage_condition");

                    b.Property<string>("disadvantageCondition")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("disadvantage_condition");

                    b.Property<string>("traitTrigger")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("trait_trigger");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId")
                        .HasDatabaseName("IX_feature_monster_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_feature_title");

                    b.ToTable("traits", "public");
                });

            modelBuilder.Entity("TWP.Api.Core.DbEntities.ActionDbEntity", b =>
                {
                    b.HasOne("TWP.Api.Core.DbEntities.Monster5eDbEntity", "Monster")
                        .WithMany("Actions")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("TWP.Api.Core.DbEntities.Symbarum5eDbEntity", b =>
                {
                    b.HasOne("TWP.Api.Core.DbEntities.Monster5eDbEntity", "Monster")
                        .WithOne("Symbarum5e")
                        .HasForeignKey("TWP.Api.Core.DbEntities.Symbarum5eDbEntity", "MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("TWP.Api.Core.DbEntities.TraitDbEntity", b =>
                {
                    b.HasOne("TWP.Api.Core.DbEntities.Monster5eDbEntity", "Monster")
                        .WithMany("Traits")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("TWP.Api.Core.DbEntities.Monster5eDbEntity", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Symbarum5e");

                    b.Navigation("Traits");
                });
#pragma warning restore 612, 618
        }
    }
}
