-- Insert statements for all monsters
INSERT INTO public."AideddMonsters"("Id", "Name", "CR", "Type", "Size", "AC", "HP", "Speed", "Alignment", "Legendary", "Habitat", "Source") VALUES
(gen_random_uuid(), 'Aarakocra Aeromancer', '4', 'Elemental', 'Medium', 16, 66, 'fly', 'Neutral', '', 'Mountain, Planar (Elemental Plane of Air)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Aarakocra Skirmisher', '1/4', 'Elemental', 'Medium', 12, 11, 'fly', 'Neutral', '', 'Mountain, Planar (Elemental Plane of Air)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Aberrant Cultist', '8', 'Humanoid', 'Medium or Small', 14, 137, '', 'Neutral Evil', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Aberrant Spirit', 'None', 'Aberration', 'Medium', 11, 40, 'fly', 'Neutral', '', '', 'Player´s Handbook 2024'),
(gen_random_uuid(), 'Aboleth', '10', 'Aberration', 'Large', 17, 150, 'swim', 'Lawful Evil', 'Legendary', 'Underdark, Underwater', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Abominable Yeti', '9', 'Monstrosity', 'Huge', 15, 137, '', 'Chaotic Evil', '', 'Arctic', 'Monster Manual 2024'),
(gen_random_uuid(), 'Adult Black Dragon', '14', 'Dragon (Chromatic)', 'Huge', 19, 195, 'fly, swim', 'Chaotic Evil', 'Legendary', 'Swamp', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Adult Blue Dragon', '16', 'Dragon (Chromatic)', 'Huge', 19, 212, 'fly', 'Lawful Evil', 'Legendary', 'Coastal, Desert', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Adult Brass Dragon', '13', 'Dragon (Metallic)', 'Huge', 18, 172, 'fly', 'Chaotic Good', 'Legendary', 'Desert', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Adult Bronze Dragon', '15', 'Dragon (Metallic)', 'Huge', 18, 212, 'fly, swim', 'Lawful Good', 'Legendary', 'Coastal', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Adult Copper Dragon', '14', 'Dragon (Metallic)', 'Huge', 18, 184, 'fly', 'Chaotic Good', 'Legendary', 'Hill', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Adult Gold Dragon', '17', 'Dragon (Metallic)', 'Huge', 19, 243, 'fly, swim', 'Lawful Good', 'Legendary', 'Forest, Grassland', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Adult Green Dragon', '15', 'Dragon (Chromatic)', 'Huge', 19, 207, 'fly, swim', 'Lawful Evil', 'Legendary', 'Forest', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Adult Red Dragon', '17', 'Dragon (Chromatic)', 'Huge', 19, 256, 'fly', 'Chaotic Evil', 'Legendary', 'Hill, Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Adult Silver Dragon', '16', 'Dragon (Metallic)', 'Huge', 19, 216, 'fly', 'Lawful Good', 'Legendary', 'Mountain, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Adult White Dragon', '13', 'Dragon (Chromatic)', 'Huge', 18, 200, 'fly, swim', 'Chaotic Evil', 'Legendary', 'Arctic', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Air Elemental', '5', 'Elemental', 'Large', 15, 90, 'fly', 'Neutral', '', 'Desert, Mountain, Planar (Elemental Plane of Air)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Allosaurus', '2', 'Beast (Dinosaur)', 'Large', 13, 51, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ancient Black Dragon', '21', 'Dragon (Chromatic)', 'Gargantuan', 22, 367, 'fly, swim', 'Chaotic Evil', 'Legendary', 'Swamp', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ancient Blue Dragon', '23', 'Dragon (Chromatic)', 'Gargantuan', 22, 481, 'fly', 'Lawful Evil', 'Legendary', 'Coastal, Desert', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ancient Brass Dragon', '20', 'Dragon (Metallic)', 'Gargantuan', 20, 332, 'fly', 'Chaotic Good', 'Legendary', 'Desert', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ancient Bronze Dragon', '22', 'Dragon (Metallic)', 'Gargantuan', 22, 444, 'fly, swim', 'Lawful Good', 'Legendary', 'Coastal', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ancient Copper Dragon', '21', 'Dragon (Metallic)', 'Gargantuan', 21, 367, 'fly', 'Chaotic Good', 'Legendary', 'Hill', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ancient Gold Dragon', '24', 'Dragon (Metallic)', 'Gargantuan', 22, 546, 'fly, swim', 'Lawful Good', 'Legendary', 'Forest, Grassland', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ancient Green Dragon', '22', 'Dragon (Chromatic)', 'Gargantuan', 21, 402, 'fly, swim', 'Lawful Evil', 'Legendary', 'Forest', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ancient Red Dragon', '24', 'Dragon (Chromatic)', 'Gargantuan', 22, 507, 'fly', 'Chaotic Evil', 'Legendary', 'Hill, Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ancient Silver Dragon', '23', 'Dragon (Metallic)', 'Gargantuan', 22, 468, 'fly', 'Lawful Good', 'Legendary', 'Mountain, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ancient White Dragon', '20', 'Dragon (Chromatic)', 'Gargantuan', 20, 333, 'fly, swim', 'Chaotic Evil', 'Legendary', 'Arctic', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Animal Lord', '20', 'Celestial', 'Medium', 19, 323, 'fly, swim', 'Neutral', 'Legendary', 'Planar (Beastlands)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Animated Armor', '1', 'Construct', 'Medium', 18, 33, '', 'Unaligned', '', 'Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Animated Broom', '1/4', 'Construct', 'Small', 15, 14, 'fly', 'Unaligned', '', 'Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Animated Flying Sword', '1/4', 'Construct', 'Small', 17, 14, 'fly', 'Unaligned', '', 'Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Animated Object', 'None', 'Construct', 'Huge or Smaller', 15, 10, '', 'Unaligned', '', '', 'Player´s Handbook 2024'),
(gen_random_uuid(), 'Animated Rug of Smothering', '2', 'Construct', 'Large', 12, 27, '', 'Unaligned', '', 'Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ankheg', '2', 'Monstrosity', 'Large', 14, 45, '', 'Unaligned', '', 'Forest, Grassland', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ankylosaurus', '3', 'Beast (Dinosaur)', 'Huge', 15, 68, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ape', '1/2', 'Beast', 'Medium', 12, 19, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Arcanaloth', '12', 'Fiend (Yugoloth)', 'Medium', 18, 175, 'fly', 'Neutral Evil', '', 'Planar (Lower Planes)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Arch-hag', '21', 'Fey', 'Large', 20, 333, '', 'Neutral Evil', 'Legendary', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Archelon', '4', 'Beast (Dinosaur)', 'Huge', 17, 90, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Archmage', '12', 'Humanoid (Wizard)', 'Medium or Small', 17, 170, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Archpriest', '12', 'Humanoid (Cleric)', 'Medium or Small', 16, 240, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Assassin', '8', 'Humanoid', 'Medium or Small', 16, 97, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Awakened Shrub', '0', 'Plant', 'Small', 9, 10, '', 'Neutral', '', 'Forest', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Awakened Tree', '2', 'Plant', 'Huge', 13, 59, '', 'Neutral', '', 'Forest', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Axe Beak', '1/4', 'Monstrosity', 'Large', 11, 19, '', 'Unaligned', '', 'Arctic, Grassland, Hill', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Azer Pyromancer', '6', 'Elemental', 'Medium', 18, 97, '', 'Lawful Neutral', '', 'Mountain, Planar (Elemental Plane of Fire)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Azer Sentinel', '2', 'Elemental', 'Medium', 17, 39, '', 'Lawful Neutral', '', 'Mountain, Planar (Elemental Plane of Fire)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Baboon', '0', 'Beast', 'Small', 12, 3, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Badger', '0', 'Beast', 'Tiny', 11, 5, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Balor', '19', 'Fiend (Demon)', 'Huge', 19, 287, 'fly', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Bandit', '1/8', 'Humanoid', 'Medium or Small', 12, 11, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Bandit Captain', '2', 'Humanoid', 'Medium or Small', 15, 52, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Bandit Crime Lord', '11', 'Humanoid', 'Medium or Small', 17, 169, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Bandit Deceiver', '7', 'Humanoid', 'Medium or Small', 16, 130, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Banshee', '4', 'Undead', 'Medium', 12, 54, 'fly', 'Chaotic Evil', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Barbed Devil', '5', 'Fiend (Devil)', 'Medium', 15, 110, '', 'Lawful Evil', '', 'Planar (Nine Hells)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Barlgura', '5', 'Fiend (Demon)', 'Large', 15, 85, '', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Basilisk', '3', 'Monstrosity', 'Medium', 15, 52, '', 'Unaligned', '', 'Mountain, Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Bat', '0', 'Beast', 'Tiny', 12, 1, 'fly', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Bearded Devil', '3', 'Fiend (Devil)', 'Medium', 13, 58, '', 'Lawful Evil', '', 'Planar (Nine Hells)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Behir', '11', 'Monstrosity', 'Huge', 17, 168, '', 'Neutral Evil', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Beholder', '13', 'Aberration', 'Large', 18, 190, 'fly', 'Lawful Evil', 'Legendary', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Beholder Zombie', '5', 'Undead', 'Large', 15, 93, 'fly', 'Neutral Evil', '', 'Planar (Shadowfell), Underdark, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Berserker', '2', 'Humanoid', 'Medium or Small', 13, 67, '', 'Any Alignment', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Berserker Commander', '8', 'Humanoid', 'Medium or Small', 16, 136, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Bestial Spirit', 'None', 'Beast', 'Small', 11, 20, 'fly, swim', 'Neutral', '', '', 'Player´s Handbook 2024'),
(gen_random_uuid(), 'Black Bear', '1/2', 'Beast', 'Medium', 11, 19, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Black Dragon Wyrmling', '2', 'Dragon (Chromatic)', 'Medium', 17, 33, 'fly, swim', 'Chaotic Evil', '', 'Swamp', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Black Pudding', '4', 'Ooze', 'Large', 7, 68, '', 'Unaligned', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Blink Dog', '1/4', 'Fey', 'Medium', 13, 16, '', 'Lawful Good', '', 'Forest, Planar (Feywild)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Blob of Annihilation', '23', 'Ooze (Titan)', 'Gargantuan', 18, 448, '', 'Neutral Evil', 'Legendary', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Blood Hawk', '1/8', 'Beast', 'Small', 12, 7, 'fly', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Blue Dragon Wyrmling', '3', 'Dragon (Chromatic)', 'Medium', 17, 65, 'fly', 'Lawful Evil', '', 'Coastal, Desert', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Blue Slaad', '7', 'Aberration', 'Large', 15, 133, '', 'Chaotic Neutral', '', 'Planar (Limbo)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Boar', '1/4', 'Beast', 'Medium', 11, 13, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Bone Devil', '9', 'Fiend (Devil)', 'Large', 16, 161, 'fly', 'Lawful Evil', '', 'Planar (Nine Hells)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Bone Naga', '4', 'Undead', 'Large', 15, 65, '', 'Neutral Evil', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Brass Dragon Wyrmling', '1', 'Dragon (Metallic)', 'Medium', 15, 22, 'fly', 'Chaotic Good', '', 'Desert', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Brazen Gorgon', '9', 'Construct', 'Large', 19, 161, '', 'Unaligned', '', 'Forest, Grassland, Hill', 'Monster Manual 2024'),
(gen_random_uuid(), 'Bronze Dragon Wyrmling', '2', 'Dragon (Metallic)', 'Medium', 15, 39, 'fly, swim', 'Lawful Good', '', 'Coastal', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Brown Bear', '1', 'Beast', 'Large', 11, 22, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Bugbear Stalker', '3', 'Fey (Goblinoid)', 'Medium', 15, 65, '', 'Chaotic Evil', '', 'Forest, Grassland, Planar (Feywild), Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Bugbear Warrior', '1', 'Fey (Goblinoid)', 'Medium', 14, 33, '', 'Chaotic Evil', '', 'Forest, Grassland, Planar (Feywild), Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Bulette', '5', 'Monstrosity', 'Large', 17, 94, '', 'Unaligned', '', 'Grassland, Hill, Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Bulette Pup', '2', 'Monstrosity', 'Medium', 16, 45, '', 'Unaligned', '', 'Grassland, Hill, Mountain', 'Monster Manual 2024'),
(gen_random_uuid(), 'Bullywug Bog Sage', '4', 'Fey', 'Medium', 16, 52, 'swim', 'Neutral', '', 'Swamp', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Bullywug Warrior', '1/4', 'Fey', 'Medium', 15, 11, 'swim', 'Neutral', '', 'Swamp', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Cambion', '5', 'Fiend', 'Medium', 19, 105, 'fly', 'Neutral Evil', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Camel', '1/8', 'Beast', 'Large', 10, 17, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Carrion Crawler', '2', 'Monstrosity', 'Large', 13, 51, '', 'Unaligned', '', 'Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Cat', '0', 'Beast', 'Tiny', 12, 2, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Celestial Spirit', 'None', 'Celestial', 'Large', 11, 40, 'fly', 'Neutral', '', '', 'Player´s Handbook 2024'),
(gen_random_uuid(), 'Centaur Trooper', '2', 'Fey', 'Large', 16, 45, '', 'Neutral Good', '', 'Forest, Grassland, Planar (Feywild)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Centaur Warden', '7', 'Fey', 'Large', 16, 105, '', 'Neutral Good', '', 'Forest, Grassland, Planar (Feywild)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Chain Devil', '8', 'Fiend (Devil)', 'Medium', 15, 85, '', 'Lawful Evil', '', 'Planar (Nine Hells)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Chasme', '6', 'Fiend (Demon)', 'Large', 15, 78, 'fly', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Chimera', '6', 'Monstrosity', 'Large', 14, 114, 'fly', 'Chaotic Evil', '', 'Grassland, Hill, Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Chuul', '4', 'Aberration', 'Large', 16, 76, 'swim', 'Chaotic Evil', '', 'Coastal, Swamp, Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Clay Golem', '9', 'Construct', 'Large', 14, 123, '', 'Unaligned', '', 'Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Cloaker', '8', 'Aberration', 'Large', 14, 91, 'fly', 'Chaotic Neutral', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Cloud Giant', '9', 'Giant', 'Huge', 14, 200, 'fly', 'Neutral', '', 'Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Cockatrice', '1/2', 'Monstrosity', 'Small', 11, 22, 'fly', 'Unaligned', '', 'Grassland', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Cockatrice Regent', '8', 'Monstrosity', 'Large', 15, 136, 'fly', 'Unaligned', '', 'Grassland', 'Monster Manual 2024'),
(gen_random_uuid(), 'Colossus', '25', 'Construct (Titan)', 'Gargantuan', 23, 553, '', 'Unaligned', 'Legendary', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Commoner', '0', 'Humanoid', 'Medium or Small', 10, 4, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Constrictor Snake', '1/4', 'Beast', 'Large', 13, 13, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Construct Spirit', 'None', 'Construct', 'Medium', 13, 40, '', 'Neutral', '', '', 'Player´s Handbook 2024'),
(gen_random_uuid(), 'Copper Dragon Wyrmling', '1', 'Dragon (Metallic)', 'Medium', 16, 22, 'fly', 'Chaotic Good', '', 'Hill', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Couatl', '4', 'Celestial', 'Medium', 19, 60, 'fly', 'Lawful Good', '', 'Desert, Forest, Grassland, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Crab', '0', 'Beast', 'Tiny', 11, 3, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Crawling Claw', '0', 'Undead', 'Tiny', 12, 2, '', 'Neutral Evil', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Crocodile', '1/2', 'Beast', 'Large', 12, 13, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Cultist', '1/8', 'Humanoid', 'Medium or Small', 12, 9, '', 'Any Alignment', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Cultist Fanatic', '2', 'Humanoid', 'Medium or Small', 13, 44, '', 'Any Alignment', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Cultist Hierophant', '10', 'Humanoid', 'Medium or Small', 16, 144, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Cyclops Oracle', '10', 'Giant', 'Huge', 16, 207, '', 'Chaotic Neutral', '', 'Coastal, Desert, Grassland, Hill, Mountain, Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Cyclops Sentry', '6', 'Giant', 'Huge', 14, 138, '', 'Chaotic Neutral', '', 'Coastal, Desert, Grassland, Hill, Mountain, Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Dao', '11', 'Elemental (Genie)', 'Large', 18, 200, 'fly', 'Neutral', '', 'Planar (Elemental Plane of Earth), Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Darkmantle', '1/2', 'Aberration', 'Small', 11, 22, 'fly', 'Unaligned', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Death Cultist', '8', 'Humanoid', 'Medium or Small', 17, 127, '', 'Neutral Evil', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Death Dog', '1', 'Monstrosity', 'Medium', 12, 39, '', 'Neutral Evil', '', 'Desert', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Death Knight', '17', 'Undead', 'Medium or Small', 20, 199, '', 'Chaotic Evil', 'Legendary', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Death Knight Aspirant', '11', 'Undead', 'Medium or Small', 20, 178, '', 'Chaotic Evil', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Death Slaad', '10', 'Aberration', 'Medium', 18, 178, '', 'Chaotic Evil', '', 'Planar (Limbo)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Death Tyrant', '14', 'Undead (Beholder)', 'Large', 19, 195, 'fly', 'Lawful Evil', 'Legendary', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Deer', '0', 'Beast', 'Medium', 13, 4, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Demilich', '18', 'Undead', 'Tiny', 20, 180, 'fly', 'Neutral Evil', 'Legendary', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Deva', '10', 'Celestial (Angel)', 'Medium', 17, 229, 'fly', 'Lawful Good', '', 'Planar (Upper Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Dire Wolf', '1', 'Beast', 'Large', 14, 22, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Dire Worg', '10', 'Fey', 'Huge', 16, 147, '', 'Neutral Evil', '', 'Forest, Grassland, Hill, Planar (Feywild)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Displacer Beast', '3', 'Monstrosity', 'Large', 13, 76, '', 'Lawful Evil', '', 'Forest', 'Monster Manual 2024'),
(gen_random_uuid(), 'Djinni', '11', 'Elemental (Genie)', 'Large', 17, 218, 'fly', 'Chaotic Good', '', 'Coastal, Planar (Elemental Plane of Air)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Doppelganger', '3', 'Monstrosity', 'Medium', 14, 52, '', 'Neutral', '', 'Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Dracolich', '17', 'Undead', 'Huge or Gargantuan', 20, 225, 'fly', 'Lawful Evil', 'Legendary', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Draconic Spirit', 'None', 'Dragon', 'Large', 14, 50, 'fly, swim', 'Neutral', '', '', 'Player´s Handbook 2024 (BR)'),
(gen_random_uuid(), 'Draft Horse', '1/4', 'Beast', 'Large', 10, 15, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Dragon Turtle', '17', 'Dragon', 'Gargantuan', 20, 356, 'swim', 'Neutral', '', 'Coastal, Underwater', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Dretch', '1/4', 'Fiend (Demon)', 'Small', 11, 18, '', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Drider', '6', 'Monstrosity', 'Large', 19, 123, '', 'Chaotic Evil', '', 'Forest, Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Druid', '2', 'Humanoid', 'Medium or Small', 13, 44, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Dryad', '1', 'Fey', 'Medium', 16, 22, '', 'Neutral', '', 'Forest', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Dust Mephit', '1/2', 'Elemental', 'Small', 12, 17, 'fly', 'Neutral Evil', '', 'Planar (Elemental Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Eagle', '0', 'Beast', 'Small', 12, 4, 'fly', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Earth Elemental', '5', 'Elemental', 'Large', 17, 147, '', 'Neutral', '', 'Mountain, Planar (Elemental Plane of Earth), Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Efreeti', '11', 'Elemental (Genie)', 'Large', 17, 212, 'fly', 'Neutral', '', 'Desert, Planar (Elemental Plane of Fire)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Elemental Cataclysm', '22', 'Elemental (Titan)', 'Gargantuan', 20, 370, 'fly, swim', 'Chaotic Neutral', 'Legendary', 'Planar (Elemental Chaos)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Elemental Cultist', '8', 'Humanoid', 'Medium or Small', 16, 135, '', 'Chaotic Evil', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Elemental Spirit', 'None', 'Elemental', 'Medium', 11, 50, 'fly, swim', 'Neutral', '', '', 'Player´s Handbook 2024'),
(gen_random_uuid(), 'Elephant', '4', 'Beast', 'Huge', 12, 76, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Elk', '1/4', 'Beast', 'Large', 10, 11, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Empyrean', '23', 'Celestial or Fiend (Titan)', 'Huge', 22, 346, 'fly, swim', 'Neutral', 'Legendary', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Empyrean Iota', '1', 'Celestial or Fiend (Titan)', 'Medium', 13, 22, 'fly', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Erinyes', '12', 'Fiend (Devil)', 'Medium', 18, 178, 'fly', 'Lawful Evil', '', 'Planar (Nine Hells)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ettercap', '2', 'Monstrosity', 'Medium', 13, 44, '', 'Neutral Evil', '', 'Forest', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ettin', '4', 'Giant', 'Large', 12, 85, '', 'Chaotic Evil', '', 'Hill, Mountain, Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Faerie Dragon Adult', '2', 'Dragon', 'Tiny', 15, 35, 'fly', 'Chaotic Good', '', 'Forest', 'Monster Manual 2024'),
(gen_random_uuid(), 'Faerie Dragon Youth', '1', 'Dragon', 'Tiny', 13, 21, 'fly', 'Chaotic Good', '', 'Forest', 'Monster Manual 2024'),
(gen_random_uuid(), 'Fey Spirit', 'None', 'Fey', 'Small', 12, 30, 'fly', 'Neutral', '', '', 'Player´s Handbook 2024'),
(gen_random_uuid(), 'Fiend Cultist', '8', 'Humanoid', 'Medium or Small', 16, 127, '', 'Neutral Evil', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Fiendish Spirit', 'None', 'Fiend', 'Large', 12, 50, 'fly', 'Neutral', '', '', 'Player´s Handbook 2024'),
(gen_random_uuid(), 'Fire Elemental', '5', 'Elemental', 'Large', 13, 93, '', 'Neutral', '', 'Desert, Planar (Elemental Plane of Fire)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Fire Giant', '9', 'Giant', 'Huge', 18, 162, '', 'Lawful Evil', '', 'Mountain, Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Flameskull', '4', 'Undead', 'Tiny', 13, 40, 'fly', 'Neutral Evil', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Flaming Skeleton', '3', 'Undead', 'Medium', 15, 65, '', 'Lawful Evil', '', 'Planar (Shadowfell), Underdark, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Flesh Golem', '5', 'Construct', 'Medium', 9, 127, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Flumph', '1/8', 'Aberration', 'Small', 12, 7, 'fly', 'Lawful Good', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Flying Snake', '1/8', 'Monstrosity', 'Tiny', 14, 5, 'fly, swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Fomorian', '8', 'Giant', 'Huge', 14, 172, '', 'Chaotic Evil', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Frog', '0', 'Beast', 'Tiny', 11, 1, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Frost Giant', '8', 'Giant', 'Huge', 15, 149, '', 'Neutral Evil', '', 'Arctic, Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Galeb Duhr', '6', 'Elemental', 'Medium', 16, 123, '', 'Neutral', '', 'Hill, Mountain', 'Monster Manual 2024'),
(gen_random_uuid(), 'Gargoyle', '2', 'Elemental', 'Medium', 15, 67, 'fly', 'Chaotic Evil', '', 'Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Gas Spore Fungus', '1/2', 'Plant', 'Large', 8, 13, 'fly', 'Unaligned', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Gelatinous Cube', '2', 'Ooze', 'Large', 6, 63, '', 'Unaligned', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ghast', '2', 'Undead', 'Medium', 13, 36, '', 'Chaotic Evil', '', 'Swamp, Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ghast Gravecaller', '6', 'Undead', 'Medium', 16, 97, '', 'Chaotic Evil', '', 'Swamp, Underdark, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Ghost', '4', 'Undead', 'Medium', 11, 45, 'fly', 'Neutral', '', 'Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ghoul', '1', 'Undead', 'Medium', 12, 22, '', 'Chaotic Evil', '', 'Swamp, Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Ape', '7', 'Beast', 'Huge', 12, 168, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Axe Beak', '5', 'Monstrosity', 'Huge', 15, 84, '', 'Unaligned', '', 'Arctic, Grassland, Hill', 'Monster Manual 2024'),
(gen_random_uuid(), 'Giant Badger', '1/4', 'Beast', 'Medium', 13, 15, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Bat', '1/4', 'Beast', 'Large', 13, 22, 'fly', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Boar', '2', 'Beast', 'Large', 13, 42, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Centipede', '1/4', 'Beast', 'Small', 14, 9, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Constrictor Snake', '2', 'Beast', 'Huge', 12, 60, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Crab', '1/8', 'Beast', 'Medium', 15, 13, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Crocodile', '5', 'Beast', 'Huge', 14, 85, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Eagle', '1', 'Celestial', 'Large', 13, 26, 'fly', 'Neutral Good', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Elk', '2', 'Celestial', 'Huge', 14, 42, '', 'Neutral Good', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Fire Beetle', '0', 'Beast', 'Small', 13, 4, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Frog', '1/4', 'Beast', 'Medium', 11, 18, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Goat', '1/2', 'Beast', 'Large', 11, 19, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Hyena', '1', 'Beast', 'Large', 12, 45, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Insect', 'None', 'Beast', 'Large', 11, 30, 'fly', 'Unaligned', '', '', 'Player´s Handbook 2024 (BR)'),
(gen_random_uuid(), 'Giant Lizard', '1/4', 'Beast', 'Large', 12, 19, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Octopus', '1', 'Beast', 'Large', 11, 45, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Owl', '1/4', 'Celestial', 'Large', 12, 19, 'fly', 'Neutral', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Rat', '1/8', 'Beast', 'Small', 13, 7, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Scorpion', '3', 'Beast', 'Large', 15, 52, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Seahorse', '1/2', 'Beast', 'Large', 14, 16, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Shark', '5', 'Beast', 'Huge', 13, 92, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Spider', '1', 'Beast', 'Large', 14, 26, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Squid', '6', 'Beast', 'Huge', 12, 120, 'swim', 'Unaligned', '', '', 'Monster Manual 2024'),
(gen_random_uuid(), 'Giant Toad', '1', 'Beast', 'Large', 11, 39, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Venomous Snake', '1/4', 'Beast', 'Medium', 14, 11, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Vulture', '1', 'Monstrosity', 'Large', 10, 25, 'fly', 'Neutral Evil', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Wasp', '1/2', 'Beast', 'Medium', 13, 22, 'fly', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Weasel', '1/8', 'Beast', 'Medium', 13, 9, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Giant Wolf Spider', '1/4', 'Beast', 'Medium', 13, 11, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Gibbering Mouther', '2', 'Aberration', 'Medium', 9, 52, 'swim', 'Chaotic Neutral', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Githyanki Dracomancer', '16', 'Aberration (Gith)', 'Medium', 18, 255, 'fly', 'Lawful Evil', '', 'Planar (Astral Plane)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Githyanki Knight', '8', 'Aberration (Gith)', 'Medium', 18, 117, '', 'Lawful Evil', '', 'Planar (Astral Plane)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Githyanki Warrior', '3', 'Aberration (Gith)', 'Medium', 17, 49, '', 'Lawful Evil', '', 'Planar (Astral Plane)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Githzerai Monk', '2', 'Aberration (Gith)', 'Medium', 14, 38, '', 'Lawful Neutral', '', 'Planar (Limbo)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Githzerai Psion', '12', 'Aberration (Gith)', 'Medium', 18, 169, 'fly', 'Lawful Neutral', '', 'Planar (Limbo)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Githzerai Zerth', '6', 'Aberration (Gith)', 'Medium', 17, 84, '', 'Lawful Neutral', '', 'Planar (Limbo)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Glabrezu', '9', 'Fiend (Demon)', 'Large', 17, 189, '', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Gladiator', '5', 'Humanoid', 'Medium or Small', 16, 112, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Gnoll Demoniac', '8', 'Fiend', 'Medium', 16, 135, '', 'Chaotic Evil', '', 'Desert, Forest, Grassland, Hill', 'Monster Manual 2024'),
(gen_random_uuid(), 'Gnoll Fang of Yeenoghu', '4', 'Fiend', 'Medium', 14, 71, '', 'Chaotic Evil', '', 'Desert, Forest, Grassland, Hill', 'Monster Manual 2024'),
(gen_random_uuid(), 'Gnoll Pack Lord', '2', 'Fiend', 'Medium', 15, 49, '', 'Chaotic Evil', '', 'Desert, Forest, Grassland, Hill', 'Monster Manual 2024'),
(gen_random_uuid(), 'Gnoll Warrior', '1/2', 'Fiend', 'Medium', 15, 27, '', 'Chaotic Evil', '', 'Desert, Forest, Grassland, Hill', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Goat', '0', 'Beast', 'Medium', 10, 4, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Goblin Boss', '1', 'Fey (Goblinoid)', 'Small', 17, 21, '', 'Chaotic Neutral', '', 'Forest, Grassland, Hill, Planar (Acheron, Feywild), Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Goblin Hexer', '3', 'Fey (Goblinoid)', 'Small', 13, 45, '', 'Chaotic Neutral', '', 'Forest, Grassland, Hill, Planar (Acheron), Planar (Feywild), Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Goblin Minion', '1/8', 'Fey (Goblinoid)', 'Small', 12, 7, '', 'Chaotic Neutral', '', 'Forest, Grassland, Hill, Planar (Acheron, Feywild), Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Goblin Warrior', '1/4', 'Fey (Goblinoid)', 'Small', 15, 10, '', 'Chaotic Neutral', '', 'Forest, Grassland, Hill, Planar (Acheron, Feywild), Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Gold Dragon Wyrmling', '3', 'Dragon (Metallic)', 'Medium', 17, 60, 'fly, swim', 'Lawful Good', '', 'Forest, Grassland', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Gorgon', '5', 'Construct', 'Large', 19, 114, '', 'Unaligned', '', 'Forest, Grassland, Hill', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Goristro', '17', 'Fiend (Demon)', 'Huge', 19, 310, '', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Graveyard Revenant', '7', 'Undead', 'Huge', 14, 161, '', 'Neutral', '', 'Forest, Swamp, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Gray Ooze', '1/2', 'Ooze', 'Medium', 9, 22, '', 'Unaligned', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Gray Slaad', '9', 'Aberration', 'Medium', 18, 150, '', 'Chaotic Neutral', '', 'Planar (Limbo)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Green Dragon Wyrmling', '2', 'Dragon (Chromatic)', 'Medium', 17, 38, 'fly, swim', 'Lawful Evil', '', 'Forest', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Green Hag', '3', 'Fey', 'Medium', 17, 82, 'swim', 'Neutral Evil', '', 'Forest, Hill, Swamp', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Green Slaad', '8', 'Aberration', 'Large', 16, 144, '', 'Chaotic Neutral', '', 'Planar (Limbo)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Grell', '3', 'Aberration', 'Medium', 12, 55, 'fly', 'Neutral Evil', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Grick', '2', 'Aberration', 'Medium', 14, 54, '', 'Unaligned', '', 'Forest, Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Grick Ancient', '7', 'Aberration', 'Large', 18, 135, '', 'Unaligned', '', 'Forest, Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Griffon', '2', 'Monstrosity', 'Large', 12, 59, 'fly', 'Unaligned', '', 'Arctic, Coastal, Grassland, Hill, Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Grimlock', '1/4', 'Aberration', 'Medium', 11, 11, '', 'Neutral Evil', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Guard', '1/8', 'Humanoid', 'Medium or Small', 16, 11, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Guard Captain', '4', 'Humanoid', 'Medium or Small', 18, 75, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Guardian Naga', '10', 'Celestial', 'Large', 18, 136, 'swim', 'Lawful Good', '', 'Desert, Forest, Planar (Upper Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Gulthias Blight', '16', 'Plant', 'Gargantuan', 20, 264, '', 'Neutral Evil', '', 'Forest', 'Monster Manual 2024'),
(gen_random_uuid(), 'Half-Dragon', '5', 'Dragon', 'Medium', 18, 105, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Harpy', '1', 'Monstrosity', 'Medium', 11, 38, 'fly', 'Chaotic Evil', '', 'Coastal, Forest, Hill, Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Haunting Revenant', '10', 'Undead', 'Gargantuan', 20, 203, '', 'Neutral', '', 'Forest, Swamp, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Hawk', '0', 'Beast', 'Tiny', 13, 1, 'fly', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Hell Hound', '3', 'Fiend', 'Medium', 15, 58, '', 'Lawful Evil', '', 'Mountain, Planar (Lower Planes), Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Helmed Horror', '4', 'Construct', 'Medium', 20, 67, 'fly', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Hezrou', '8', 'Fiend (Demon)', 'Large', 18, 157, '', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Hill Giant', '5', 'Giant', 'Huge', 13, 105, '', 'Chaotic Evil', '', 'Hill', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Hippogriff', '1', 'Monstrosity', 'Large', 11, 26, 'fly', 'Unaligned', '', 'Grassland, Hill, Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Hippopotamus', '4', 'Beast', 'Large', 14, 82, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Hobgoblin Captain', '3', 'Fey (Goblinoid)', 'Medium', 17, 58, '', 'Lawful Evil', '', 'Desert, Forest, Grassland, Hill, Mountain, Planar (Acheron), Underdar', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Hobgoblin Warlord', '6', 'Fey (Goblinoid)', 'Medium', 20, 112, '', 'Lawful Evil', '', 'Desert, Forest, Grassland, Hill, Mountain, Planar (Acheron), Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Hobgoblin Warrior', '1/2', 'Fey (Goblinoid)', 'Medium', 18, 11, '', 'Lawful Evil', '', 'Desert, Forest, Grassland, Hill, Mountain, Planar (Acheron), Underdar', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Homunculus', '0', 'Construct', 'Tiny', 13, 4, 'fly', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Hook Horror', '3', 'Monstrosity', 'Large', 15, 75, '', 'Neutral', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Horned Devil', '11', 'Fiend (Devil)', 'Large', 18, 199, 'fly', 'Lawful Evil', '', 'Planar (Nine Hells)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Hunter Shark', '2', 'Beast', 'Large', 12, 45, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Hydra', '8', 'Monstrosity', 'Huge', 15, 184, 'swim', 'Unaligned', '', 'Coastal, Swamp', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Hyena', '0', 'Beast', 'Medium', 11, 5, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ice Devil', '14', 'Fiend (Devil)', 'Large', 18, 228, '', 'Lawful Evil', '', 'Planar (Nine Hells)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ice Mephit', '1/2', 'Elemental', 'Small', 11, 21, 'fly', 'Neutral Evil', '', 'Planar (Elemental Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Imp', '1', 'Fiend (Devil)', 'Tiny', 13, 21, 'fly', 'Lawful Evil', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Incubus', '4', 'Fiend', 'Medium', 15, 66, 'fly', 'Neutral Evil', '', 'Planar (Lower Planes), Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Intellect Devourer', '2', 'Aberration', 'Tiny', 12, 28, '', 'Lawful Evil', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Invisible Stalker', '6', 'Elemental', 'Large', 14, 97, 'fly', 'Neutral', '', 'Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Iron Golem', '16', 'Construct', 'Large', 20, 252, '', 'Unaligned', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Jackal', '0', 'Beast', 'Small', 12, 3, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Jackalwere', '1/2', 'Fiend', 'Small', 12, 18, '', 'Chaotic Evil', '', 'Desert, Grassland', 'Monster Manual 2024'),
(gen_random_uuid(), 'Juvenile Shadow Dragon', '4', 'Dragon', 'Medium', 15, 45, 'fly', 'Chaotic Evil', '', 'Planar (Shadowfell), Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Kenku', '1/4', 'Monstrosity', 'Medium', 13, 13, '', 'Neutral', '', 'Forest, Planar (Shadowfell), Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Killer Whale', '3', 'Beast', 'Huge', 12, 90, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Knight', '3', 'Humanoid', 'Medium or Small', 18, 52, '', 'Any Alignment', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Kobold Warrior', '1/8', 'Dragon', 'Small', 14, 7, '', 'Neutral', '', 'Arctic, Coastal, Desert, Forest, Hill, Mountain, Swamp, Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Kraken', '23', 'Monstrosity (Titan)', 'Gargantuan', 18, 481, 'swim', 'Chaotic Evil', 'Legendary', 'Underwater', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Kuo-Toa', '1/4', 'Aberration', 'Medium', 13, 18, 'swim', 'Neutral Evil', '', 'Coastal, Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Kuo-toa Archpriest', '6', 'Aberration', 'Medium', 13, 105, 'swim', 'Neutral Evil', '', 'Coastal, Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Kuo-toa Monitor', '3', 'Aberration', 'Medium', 13, 65, 'swim', 'Neutral Evil', '', 'Coastal, Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Kuo-toa Whip', '1', 'Aberration', 'Medium', 11, 45, 'swim', 'Neutral Evil', '', 'Coastal, Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Lacedon Ghoul', '1', 'Undead', 'Medium', 12, 22, 'swim', 'Chaotic Evil', '', 'Swamp, Underdark, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Lamia', '4', 'Fiend', 'Large', 13, 97, '', 'Chaotic Evil', '', 'Desert', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Larva', '0', 'Fiend', 'Medium', 9, 9, '', 'Neutral Evil', '', 'Planar (Lower Planes)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Lemure', '0', 'Fiend (Devil)', 'Medium', 9, 9, '', 'Lawful Evil', '', 'Planar (Nine Hells)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Lich', '21', 'Undead (Wizard)', 'Medium', 20, 315, '', 'Neutral Evil', 'Legendary', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Lion', '1', 'Beast', 'Large', 12, 22, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Lizard', '0', 'Beast', 'Tiny', 10, 2, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Lizardfolk Geomancer', '2', 'Elemental', 'Medium', 13, 33, 'swim', 'Neutral', '', 'Forest, Swamp', 'Monster Manual 2024'),
(gen_random_uuid(), 'Lizardfolk Sovereign', '4', 'Elemental', 'Medium', 15, 78, 'swim', 'Neutral', '', 'Forest, Swamp', 'Monster Manual 2024'),
(gen_random_uuid(), 'Mage', '6', 'Humanoid (Wizard)', 'Medium or Small', 15, 81, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Mage Apprentice', '2', 'Humanoid (Wizard)', 'Medium or Small', 15, 49, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Magma Mephit', '1/2', 'Elemental', 'Small', 11, 18, 'fly', 'Neutral Evil', '', 'Planar (Elemental Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Magmin', '1/2', 'Elemental', 'Small', 14, 13, '', 'Chaotic Neutral', '', 'Planar (Elemental Plane of Fire)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Mammoth', '6', 'Beast', 'Huge', 13, 126, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Manes', '1/8', 'Fiend (Demon)', 'Small', 9, 9, '', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Manes Vaporspawn', '1', 'Fiend (Demon)', 'Medium', 13, 19, '', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Manticore', '3', 'Monstrosity', 'Large', 14, 68, 'fly', 'Lawful Evil', '', 'Arctic, Coastal, Grassland, Hill, Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Marid', '11', 'Elemental (Genie)', 'Large', 17, 229, 'fly, swim', 'Chaotic Neutral', '', 'Coastal, Planar (Elemental Plane of Water), Underwater', 'Monster Manual 2024'),
(gen_random_uuid(), 'Marilith', '16', 'Fiend (Demon)', 'Large', 16, 220, '', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Mastiff', '1/8', 'Beast', 'Medium', 12, 5, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Medusa', '6', 'Monstrosity', 'Medium', 15, 127, '', 'Lawful Evil', '', 'Desert', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Merfolk Skirmisher', '1/8', 'Elemental', 'Medium', 11, 11, 'swim', 'Neutral', '', 'Coastal, Underwater', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Merfolk Wavebender', '6', 'Elemental', 'Medium', 14, 97, 'swim', 'Neutral', '', 'Coastal, Underwater', 'Monster Manual 2024'),
(gen_random_uuid(), 'Merrow', '2', 'Monstrosity', 'Large', 13, 45, 'swim', 'Chaotic Evil', '', 'Coastal, Underwater', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Mezzoloth', '5', 'Fiend (Yugoloth)', 'Medium', 18, 75, '', 'Neutral Evil', '', 'Planar (Gehenna)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Mimic', '2', 'Monstrosity', 'Medium', 12, 58, '', 'Neutral', '', 'Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Mind Flayer', '7', 'Aberration', 'Medium', 15, 99, 'fly', 'Lawful Evil', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Mind Flayer Arcanist', '11', 'Aberration', 'Medium', 16, 143, 'fly', 'Lawful Evil', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Minotaur of Baphomet', '3', 'Monstrosity', 'Large', 14, 85, '', 'Chaotic Evil', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Minotaur Skeleton', '2', 'Undead', 'Large', 12, 45, '', 'Lawful Evil', '', 'Planar (Shadowfell), Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Mud Mephit', '1/4', 'Elemental', 'Small', 11, 13, 'fly, swim', 'Neutral Evil', '', 'Planar (Elemental Planes)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Mule', '1/8', 'Beast', 'Medium', 10, 11, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Mummy', '3', 'Undead', 'Medium or Small', 11, 58, '', 'Lawful Evil', '', 'Desert, Swamp', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Mummy Lord', '15', 'Undead (Cleric)', 'Medium or Small', 17, 187, '', 'Lawful Evil', 'Legendary', 'Desert, Swamp', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Myconid Adult', '1/2', 'Plant', 'Medium', 12, 16, '', 'Lawful Neutral', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Myconid Sovereign', '2', 'Plant', 'Large', 13, 45, '', 'Lawful Neutral', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Myconid Spore Servant', '1', 'Plant', 'Medium or Small', 13, 37, '', 'Unaligned', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Myconid Sprout', '0', 'Plant', 'Small', 10, 3, '', 'Lawful Neutral', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Nalfeshnee', '13', 'Fiend (Demon)', 'Large', 18, 184, 'fly', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Needle Blight', '1/4', 'Plant', 'Medium', 12, 16, '', 'Neutral Evil', '', 'Forest', 'Monster Manual 2024'),
(gen_random_uuid(), 'Night Hag', '5', 'Fiend', 'Medium', 17, 112, '', 'Neutral Evil', '', 'Planar (Lower Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Nightmare', '3', 'Fiend', 'Large', 13, 68, 'fly', 'Neutral Evil', '', 'Planar (Lower Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Noble', '1/8', 'Humanoid', 'Medium or Small', 15, 9, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Noble Prodigy', '10', 'Humanoid', 'Medium or Small', 16, 148, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Nothic', '2', 'Aberration', 'Medium', 15, 45, '', 'Neutral Evil', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Nycaloth', '9', 'Fiend (Yugoloth)', 'Large', 18, 152, 'fly', 'Neutral Evil', '', 'Planar (Gehenna)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Ochre Jelly', '2', 'Ooze', 'Large', 8, 52, '', 'Unaligned', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Octopus', '0', 'Beast', 'Small', 12, 3, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ogre', '2', 'Giant', 'Large', 11, 68, '', 'Chaotic Evil', '', 'Arctic, Desert, Forest, Grassland, Hill, Mountain, Swamp, Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ogre Zombie', '2', 'Undead', 'Large', 8, 85, '', 'Neutral Evil', '', 'Planar (Shadowfell), Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ogrillon Ogre', '1', 'Giant', 'Large', 12, 52, '', 'Chaotic Evil', '', 'Arctic, Desert, Forest, Grassland, Hill, Mountain, Swamp, Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Oni', '7', 'Fiend', 'Large', 17, 119, 'fly', 'Lawful Evil', '', 'Forest, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Otherworldly Steed', 'None', 'Celestial or Fey or Fiend', 'Large', 10, 5, 'fly', 'Neutral', '', '', 'Player´s Handbook 2024 (BR)'),
(gen_random_uuid(), 'Otyugh', '5', 'Aberration', 'Large', 14, 104, '', 'Neutral', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Owl', '0', 'Beast', 'Tiny', 11, 1, 'fly', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Owlbear', '3', 'Monstrosity', 'Large', 13, 59, '', 'Unaligned', '', 'Forest', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Panther', '1/4', 'Beast', 'Medium', 13, 13, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Pegasus', '2', 'Celestial', 'Large', 12, 59, 'fly', 'Chaotic Good', '', 'Forest, Grassland, Hill, Planar (Upper Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Performer', '1/2', 'Humanoid', 'Medium or Small', 13, 27, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Performer Legend', '10', 'Humanoid', 'Medium or Small', 20, 162, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Performer Maestro', '6', 'Humanoid', 'Medium or Small', 18, 110, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Peryton', '2', 'Monstrosity', 'Medium', 13, 33, 'fly', 'Chaotic Evil', '', 'Hill, Mountain', 'Monster Manual 2024'),
(gen_random_uuid(), 'Phase Spider', '3', 'Monstrosity', 'Large', 14, 45, '', 'Unaligned', '', 'Desert, Forest, Grassland, Hill, Planar (Ethereal Plane), Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Piercer', '1/2', 'Aberration', 'Medium', 15, 22, '', 'Unaligned', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Piranha', '0', 'Beast', 'Tiny', 13, 1, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Pirate', '1', 'Humanoid', 'Medium or Small', 14, 27, '', 'Any Alignment', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Pirate Admiral', '12', 'Humanoid', 'Medium or Small', 20, 182, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Pirate Captain', '6', 'Humanoid', 'Medium or Small', 17, 84, '', 'Any Alignment', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Pit Fiend', '20', 'Fiend (Devil)', 'Large', 21, 337, 'fly', 'Lawful Evil', '', 'Planar (Nine Hells)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Pixie', '1/4', 'Fey', 'Tiny', 15, 9, 'fly', 'Neutral Good', '', 'Forest, Planar (Feywild)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Pixie Wonderbringer', '5', 'Fey', 'Tiny', 15, 60, 'fly', 'Neutral Good', '', 'Forest, Planar (Feywild)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Planetar', '16', 'Celestial (Angel)', 'Large', 19, 262, 'fly', 'Lawful Good', '', 'Planar (Upper Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Plesiosaurus', '2', 'Beast (Dinosaur)', 'Large', 13, 68, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Polar Bear', '2', 'Beast', 'Large', 12, 42, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Poltergeist', '2', 'Undead', 'Medium or Small', 12, 22, 'fly', 'Chaotic Neutral', '', 'Underdark, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Pony', '1/8', 'Beast', 'Medium', 10, 11, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Priest', '2', 'Humanoid (Cleric)', 'Medium or Small', 13, 38, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Priest Acolyte', '1/4', 'Humanoid (Cleric)', 'Medium or Small', 13, 11, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Primeval Owlbear', '7', 'Monstrosity', 'Huge', 16, 126, 'fly', 'Unaligned', '', 'Forest', 'Monster Manual 2024'),
(gen_random_uuid(), 'Pseudodragon', '1/4', 'Dragon', 'Tiny', 14, 10, 'fly', 'Neutral Good', '', 'Coastal, Desert, Forest, Hill, Mountain, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Psychic Gray Ooze', '1', 'Ooze', 'Medium', 9, 37, '', 'Unaligned', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Pteranodon', '1/4', 'Beast (Dinosaur)', 'Medium', 13, 13, 'fly', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Purple Worm', '15', 'Monstrosity', 'Gargantuan', 18, 247, '', 'Unaligned', '', 'Desert, Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Quaggoth', '2', 'Monstrosity', 'Medium', 13, 45, '', 'Chaotic Neutral', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Quaggoth Thonot', '3', 'Monstrosity', 'Medium', 15, 67, '', 'Chaotic Neutral', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Quasit', '1', 'Fiend (Demon)', 'Tiny', 13, 25, '', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Questing Knight', '12', 'Humanoid', 'Medium or Small', 18, 202, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Rakshasa', '13', 'Fiend', 'Medium', 17, 221, '', 'Lawful Evil', '', 'Planar (Nine Hells), Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Rat', '0', 'Beast', 'Tiny', 10, 1, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Raven', '0', 'Beast', 'Tiny', 12, 2, 'fly', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Red Dragon Wyrmling', '4', 'Dragon (Chromatic)', 'Medium', 17, 75, 'fly', 'Chaotic Evil', '', 'Hill, Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Red Slaad', '5', 'Aberration', 'Large', 14, 93, '', 'Chaotic Neutral', '', 'Planar (Limbo)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Reef Shark', '1/2', 'Beast', 'Medium', 12, 22, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Remorhaz', '11', 'Monstrosity', 'Huge', 17, 195, '', 'Unaligned', '', 'Arctic', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Revenant', '5', 'Undead', 'Medium', 13, 127, '', 'Neutral', '', 'Forest, Swamp, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Rhinoceros', '2', 'Beast', 'Large', 13, 45, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Riding Horse', '1/4', 'Beast', 'Large', 11, 13, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Roc', '11', 'Monstrosity', 'Gargantuan', 15, 248, 'fly', 'Unaligned', '', 'Arctic, Coastal, Desert, Hill, Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Roper', '5', 'Aberration', 'Large', 20, 93, '', 'Neutral Evil', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Rust Monster', '1/2', 'Monstrosity', 'Medium', 14, 33, '', 'Unaligned', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Saber-Toothed Tiger', '2', 'Beast', 'Large', 13, 52, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Sahuagin Baron', '5', 'Fiend', 'Large', 16, 76, 'swim', 'Lawful Evil', '', 'Coastal, Underwater', 'Monster Manual 2024'),
(gen_random_uuid(), 'Sahuagin Priest', '2', 'Fiend', 'Medium', 12, 38, 'swim', 'Lawful Evil', '', 'Coastal, Underwater', 'Monster Manual 2024'),
(gen_random_uuid(), 'Sahuagin Warrior', '1/2', 'Fiend', 'Medium', 12, 22, 'swim', 'Lawful Evil', '', 'Coastal, Underwater', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Salamander', '5', 'Elemental', 'Large', 15, 90, '', 'Neutral Evil', '', 'Planar (Elemental Plane of Fire), Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Salamander Fire Snake', '1', 'Elemental', 'Medium', 14, 27, '', 'Neutral Evil', '', 'Planar (Elemental Plane of Fire), Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Salamander Inferno Master', '15', 'Elemental', 'Large', 18, 256, '', 'Neutral Evil', '', 'Planar (Elemental Plane of Fire), Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Satyr', '1/2', 'Fey', 'Medium', 13, 31, '', 'Chaotic Neutral', '', 'Forest, Planar (Feywild)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Satyr Revelmaster', '6', 'Fey', 'Medium', 17, 82, '', 'Chaotic Neutral', '', 'Forest, Planar (Feywild)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Scarecrow', '1', 'Construct', 'Medium', 11, 27, '', 'Chaotic Evil', '', 'Grassland', 'Monster Manual 2024'),
(gen_random_uuid(), 'Scorpion', '0', 'Beast', 'Tiny', 11, 1, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Scout', '1/2', 'Humanoid', 'Medium or Small', 13, 16, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Scout Captain', '3', 'Humanoid', 'Medium or Small', 15, 66, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Sea Hag', '2', 'Fey', 'Medium', 14, 52, 'swim', 'Chaotic Evil', '', 'Coastal, Underwater', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Seahorse', '0', 'Beast', 'Tiny', 12, 1, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Shadow', '1/2', 'Undead', 'Medium', 12, 27, '', 'Chaotic Evil', '', 'Planar (Shadowfell), Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Shadow Demon', '4', 'Fiend (Demon)', 'Medium', 14, 66, 'fly', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Shadow Dragon', '13', 'Dragon', 'Huge', 16, 189, 'fly', 'Chaotic Evil', 'Legendary', 'Planar (Shadowfell), Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Shambling Mound', '5', 'Plant', 'Large', 15, 110, 'swim', 'Unaligned', '', 'Forest, Swamp', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Shield Guardian', '7', 'Construct', 'Large', 17, 142, '', 'Unaligned', '', 'Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Shrieker Fungus', '0', 'Plant', 'Medium', 5, 13, '', 'Unaligned', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Silver Dragon Wyrmling', '2', 'Dragon (Metallic)', 'Medium', 17, 45, 'fly', 'Lawful Good', '', 'Mountain, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Skeleton', '1/4', 'Undead', 'Medium', 14, 13, '', 'Lawful Evil', '', 'Planar (Shadowfell), Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Slaad Tadpole', '1/8', 'Aberration', 'Tiny', 12, 7, '', 'Chaotic Neutral', '', 'Planar (Limbo)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Smoke Mephit', '1/4', 'Elemental', 'Small', 12, 13, 'fly', 'Neutral Evil', '', 'Planar (Elemental Planes)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Solar', '21', 'Celestial (Angel)', 'Large', 21, 297, 'fly', 'Lawful Good', 'Legendary', 'Planar (Upper Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Spectator', '3', 'Aberration (Beholder)', 'Medium', 14, 45, 'fly', 'Lawful Neutral', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Specter', '1', 'Undead', 'Medium', 12, 22, 'fly', 'Chaotic Evil', '', 'Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Sphinx of Lore', '11', 'Celestial', 'Large', 17, 170, 'fly', 'Lawful Neutral', 'Legendary', 'Desert, Planar (Upper Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Sphinx of Secrets', '8', 'Celestial', 'Large', 16, 136, 'fly', 'Lawful Neutral', '', 'Desert, Planar (Upper Planes)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Sphinx of Valor', '17', 'Celestial', 'Large', 17, 199, 'fly', 'Lawful Neutral', 'Legendary', 'Desert, Planar (Upper Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Sphinx of Wonder', '1', 'Celestial', 'Tiny', 13, 24, 'fly', 'Lawful Good', '', 'Desert, Planar (Upper Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Spider', '0', 'Beast', 'Tiny', 12, 1, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Spined Devil', '2', 'Fiend (Devil)', 'Small', 13, 45, 'fly', 'Lawful Evil', '', 'Planar (Nine Hells)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Spirit Naga', '8', 'Fiend', 'Large', 17, 135, '', 'Chaotic Evil', '', 'Planar (Lower Planes), Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Sprite', '1/4', 'Fey', 'Tiny', 15, 10, 'fly', 'Neutral Good', '', 'Forest, Planar (Feywild)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Spy', '1', 'Humanoid', 'Medium or Small', 12, 27, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Spy Master', '10', 'Humanoid', 'Medium or Small', 19, 137, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Steam Mephit', '1/4', 'Elemental', 'Small', 10, 17, 'fly', 'Neutral Evil', '', 'Planar (Elemental Planes)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Stirge', '1/8', 'Monstrosity', 'Tiny', 13, 5, 'fly', 'Unaligned', '', 'Desert, Forest, Grassland, Hill, Mountain, Swamp, Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Stone Giant', '7', 'Giant', 'Huge', 17, 126, '', 'Neutral', '', 'Mountain, Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Stone Golem', '10', 'Construct', 'Large', 18, 220, '', 'Unaligned', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Storm Giant', '13', 'Giant', 'Huge', 16, 230, 'fly, swim', 'Chaotic Good', '', 'Coastal, Underwater', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Succubus', '4', 'Fiend', 'Medium', 15, 71, 'fly', 'Neutral Evil', '', 'Planar (Lower Planes), Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Swarm of Bats', '1/4', 'Swarm of Tiny Beasts', 'Large', 12, 11, 'fly', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Swarm of Crawling Claws', '3', 'Swarm of Tiny Undead', 'Medium', 12, 49, '', 'Neutral Evil', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Swarm of Dretches', '4', 'Swarm of Small Fiends (Demon)', 'Large', 12, 45, '', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Swarm of Insects', '1/2', 'Swarm of Tiny Beasts', 'Medium', 11, 19, 'fly', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Swarm of Larvae', '1', 'Swarm of Medium Fiends', 'Large', 13, 22, '', 'Neutral Evil', '', 'Planar (Lower Planes)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Swarm of Lemures', '3', 'Swarm of Medium Fiends (Devil)', 'Large', 12, 45, '', 'Lawful Evil', '', 'Planar (Nine Hells)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Swarm of Piranhas', '1', 'Swarm of Tiny Beasts', 'Medium', 13, 28, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Swarm of Rats', '1/4', 'Swarm of Tiny Beasts', 'Medium', 10, 14, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Swarm of Ravens', '1/4', 'Swarm of Tiny Beasts', 'Medium', 12, 11, 'fly', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Swarm of Stirges', '2', 'Swarm of Tiny Monstrosities', 'Medium', 14, 36, 'fly', 'Unaligned', '', 'Desert, Forest, Grassland, Hill, Mountain, Swamp, Underdark, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Swarm of Venomous Snakes', '2', 'Swarm of Tiny Beasts', 'Medium', 14, 36, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Tarrasque', '30', 'Monstrosity (Titan)', 'Gargantuan', 25, 697, '', 'Unaligned', 'Legendary', 'Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Thri-kreen Marauder', '1', 'Monstrosity', 'Medium', 15, 33, '', 'Neutral', '', 'Desert, Grassland', 'Monster Manual 2024'),
(gen_random_uuid(), 'Thri-kreen Psion', '8', 'Monstrosity', 'Medium', 16, 149, 'fly', 'Neutral', '', 'Desert, Grassland', 'Monster Manual 2024'),
(gen_random_uuid(), 'Tiger', '1', 'Beast', 'Large', 13, 30, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Tough', '1/2', 'Humanoid', 'Medium or Small', 12, 32, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Tough Boss', '4', 'Humanoid', 'Medium or Small', 16, 82, '', 'Any Alignment', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Treant', '9', 'Plant', 'Huge', 16, 138, '', 'Chaotic Good', '', 'Forest', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Tree Blight', '7', 'Plant', 'Huge', 15, 115, '', 'Neutral Evil', '', 'Forest', 'Monster Manual 2024'),
(gen_random_uuid(), 'Triceratops', '5', 'Beast (Dinosaur)', 'Huge', 14, 114, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Troglodyte', '1/4', 'Monstrosity', 'Medium', 11, 13, '', 'Chaotic Evil', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Troll', '5', 'Giant', 'Large', 15, 94, '', 'Chaotic Evil', '', 'Arctic, Forest, Hill, Mountain, Swamp, Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Troll Limb', '1/2', 'Giant', 'Small', 13, 14, '', 'Chaotic Evil', '', 'Arctic, Forest, Hill, Mountain, Swamp, Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Twig Blight', '1/8', 'Plant', 'Small', 14, 7, '', 'Neutral Evil', '', 'Forest', 'Monster Manual 2024'),
(gen_random_uuid(), 'Tyrannosaurus Rex', '8', 'Beast (Dinosaur)', 'Huge', 13, 136, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Ultroloth', '13', 'Fiend (Yugoloth)', 'Medium', 19, 221, 'fly', 'Neutral Evil', '', 'Planar (Lower Planes)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Umber Hulk', '5', 'Monstrosity', 'Large', 18, 93, '', 'Chaotic Evil', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Undead Spirit', 'None', 'Undead', 'Medium', 11, 30, 'fly', 'Neutral', '', '', 'Player´s Handbook 2024'),
(gen_random_uuid(), 'Unicorn', '5', 'Celestial', 'Large', 12, 97, '', 'Lawful Good', 'Legendary', 'Forest, Planar (Feywild)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Vampire', '13', 'Undead', 'Medium or Small', 16, 195, '', 'Lawful Evil', 'Legendary', 'Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Vampire Familiar', '3', 'Humanoid', 'Medium or Small', 15, 65, '', 'Neutral Evil', '', 'Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Vampire Nightbringer', '8', 'Undead', 'Medium or Small', 16, 142, 'fly', 'Neutral Evil', '', 'Underdark, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Vampire Spawn', '5', 'Undead', 'Medium or Small', 16, 90, '', 'Neutral Evil', '', 'Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Vampire Umbral Lord', '15', 'Undead', 'Medium or Small', 16, 187, 'fly', 'Lawful Evil', 'Legendary', 'Underdark, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Venomous Snake', '1/8', 'Beast', 'Tiny', 12, 5, 'swim', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Vine Blight', '1/2', 'Plant', 'Medium', 12, 19, '', 'Neutral Evil', '', 'Forest', 'Monster Manual 2024'),
(gen_random_uuid(), 'Violet Fungus', '1/4', 'Plant', 'Medium', 5, 18, '', 'Unaligned', '', 'Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Violet Fungus Necrohulk', '7', 'Plant', 'Large', 17, 123, '', 'Neutral Evil', '', 'Underdark', 'Monster Manual 2024'),
(gen_random_uuid(), 'Vrock', '6', 'Fiend (Demon)', 'Large', 15, 152, 'fly', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Vulture', '0', 'Beast', 'Medium', 10, 5, 'fly', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Warhorse', '1/2', 'Beast', 'Large', 11, 19, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Warhorse Skeleton', '1/2', 'Undead', 'Large', 13, 22, '', 'Lawful Evil', '', 'Planar (Shadowfell), Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Warrior Commander', '10', 'Humanoid', 'Medium or Small', 18, 161, '', 'Neutral', '', 'Any', 'Monster Manual 2024'),
(gen_random_uuid(), 'Warrior Infantry', '1/8', 'Humanoid', 'Medium or Small', 13, 9, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Warrior Veteran', '3', 'Humanoid', 'Medium or Small', 17, 65, '', 'Neutral', '', 'Any', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Water Elemental', '5', 'Elemental', 'Large', 14, 114, 'swim', 'Neutral', '', 'Coastal, Planar (Elemental Plane of Water), Swamp, Underwater', 'Monster Manual 2024'),
(gen_random_uuid(), 'Water Weird', '3', 'Elemental', 'Large', 13, 65, 'swim', 'Neutral', '', 'Underdark, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Weasel', '0', 'Beast', 'Tiny', 13, 1, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Werebear', '5', 'Monstrosity (Lycanthrope)', 'Medium or Small', 15, 135, '', 'Neutral Good', '', 'Arctic, Forest, Hill', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Wereboar', '4', 'Monstrosity (Lycanthrope)', 'Medium or Small', 15, 97, '', 'Neutral Evil', '', 'Forest, Grassland, Hill', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Wererat', '2', 'Monstrosity (Lycanthrope)', 'Medium or Small', 13, 60, '', 'Lawful Evil', '', 'Forest, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Weretiger', '4', 'Monstrosity (Lycanthrope)', 'Medium or Small', 12, 120, '', 'Neutral', '', 'Desert, Forest, Grassland', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Werewolf', '3', 'Monstrosity (Lycanthrope)', 'Medium or Small', 15, 71, '', 'Chaotic Evil', '', 'Forest, Hill', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'White Dragon Wyrmling', '2', 'Dragon (Chromatic)', 'Medium', 16, 32, 'fly, swim', 'Chaotic Evil', '', 'Arctic', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Wight', '3', 'Undead', 'Medium', 14, 82, '', 'Neutral Evil', '', 'Desert, Planar (Shadowfell), Swamp, Underdark, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Will-o´-Wisp', '2', 'Undead', 'Tiny', 19, 27, 'fly', 'Chaotic Evil', '', 'Forest, Swamp, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Winged Kobold', '1/4', 'Dragon', 'Small', 15, 10, 'fly', 'Neutral', '', 'Arctic, Coastal, Desert, Forest, Hill, Mountain, Swamp, Underdark, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Winter Wolf', '3', 'Monstrosity', 'Large', 13, 75, '', 'Neutral Evil', '', 'Arctic', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Wolf', '1/4', 'Beast', 'Medium', 12, 11, '', 'Unaligned', '', '', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Worg', '1/2', 'Fey', 'Large', 13, 26, '', 'Neutral Evil', '', 'Forest, Grassland, Hill, Planar (Feywild)', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Wraith', '5', 'Undead', 'Medium or Small', 13, 67, 'fly', 'Neutral Evil', '', 'Planar (Shadowfell), Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Wyvern', '6', 'Dragon', 'Large', 14, 127, 'fly', 'Unaligned', '', 'Hill, Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Xorn', '5', 'Elemental', 'Medium', 19, 84, '', 'Neutral', '', 'Planar (Elemental Plane of Earth), Underdark', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Yeti', '3', 'Monstrosity', 'Large', 12, 51, '', 'Chaotic Evil', '', 'Arctic', 'Monster Manual 2024'),
(gen_random_uuid(), 'Yochlol', '10', 'Fiend (Demon)', 'Medium', 15, 153, '', 'Chaotic Evil', '', 'Planar (Abyss)', 'Monster Manual 2024'),
(gen_random_uuid(), 'Young Black Dragon', '7', 'Dragon (Chromatic)', 'Large', 18, 127, 'fly, swim', 'Chaotic Evil', '', 'Swamp', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Young Blue Dragon', '9', 'Dragon (Chromatic)', 'Large', 18, 152, 'fly', 'Lawful Evil', '', 'Coastal, Desert', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Young Brass Dragon', '6', 'Dragon (Metallic)', 'Large', 17, 110, 'fly', 'Chaotic Good', '', 'Desert', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Young Bronze Dragon', '8', 'Dragon (Metallic)', 'Large', 17, 142, 'fly, swim', 'Lawful Good', '', 'Coastal', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Young Copper Dragon', '7', 'Dragon (Metallic)', 'Large', 17, 119, 'fly', 'Chaotic Good', '', 'Hill', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Young Gold Dragon', '10', 'Dragon (Metallic)', 'Large', 18, 178, 'fly, swim', 'Lawful Good', '', 'Forest, Grassland', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Young Green Dragon', '8', 'Dragon (Chromatic)', 'Large', 18, 136, 'fly, swim', 'Lawful Evil', '', 'Forest', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Young Red Dragon', '10', 'Dragon (Chromatic)', 'Large', 18, 178, 'fly', 'Chaotic Evil', '', 'Hill, Mountain', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Young Remorhaz', '5', 'Monstrosity', 'Large', 14, 93, '', 'Unaligned', '', 'Arctic', 'Monster Manual 2024'),
(gen_random_uuid(), 'Young Silver Dragon', '9', 'Dragon (Metallic)', 'Large', 18, 168, 'fly', 'Lawful Good', '', 'Mountain, Urban', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Young White Dragon', '6', 'Dragon (Chromatic)', 'Large', 17, 123, 'fly, swim', 'Chaotic Evil', '', 'Arctic', 'Monster Manual 2024 (BR)'),
(gen_random_uuid(), 'Yuan-ti Abomination', '7', 'Monstrosity', 'Large', 15, 127, '', 'Neutral Evil', '', 'Desert, Forest, Swamp, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Yuan-ti Infiltrator', '1', 'Monstrosity', 'Medium', 11, 40, '', 'Neutral Evil', '', 'Desert, Forest, Swamp, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Yuan-ti Malison (Type 1)', '3', 'Monstrosity', 'Medium', 12, 66, '', 'Neutral Evil', '', 'Desert, Forest, Swamp, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Yuan-ti Malison (Type 2)', '3', 'Monstrosity', 'Medium', 12, 66, '', 'Neutral Evil', '', 'Desert, Forest, Swamp, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Yuan-ti Malison (Type 3)', '3', 'Monstrosity', 'Medium', 12, 66, '', 'Neutral Evil', '', 'Desert, Forest, Swamp, Urban', 'Monster Manual 2024'),
(gen_random_uuid(), 'Zombie', '1/4', 'Undead', 'Medium', 8, 15, '', 'Neutral Evil', '', 'Planar (Shadowfell), Underdark, Urban', 'Monster Manual 2024 (BR)');