[build]
builder = "dockerfile"
dockerfilePath = "./TogetherWePlayApi/TogetherWePlayApi/Dockerfile"

[deploy]
startCommand = "dotnet TWP.Api.dll"
restartPolicyType = "always"
healthcheckPath = "/health"
