[build]
builder = "dockerfile"
dockerfilePath = "./TogetherWePlayApi/TogetherWePlayApi/Dockerfile"

[deploy]
# Remove the startCommand since Docker will handle it
# startCommand = "dotnet TWP.Api.dll"
restartPolicyType = "always"
healthcheckPath = "/health"
